# Generated by Django 5.1.5 on 2025-02-02 13:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('backdrop_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('profile_path', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tmdb_id'], name='core_person_tmdb_id_4e21bd_idx'), models.Index(fields=['name'], name='core_person_name_ab6274_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('plot', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('poster_preview_url', models.URLField(blank=True, max_length=500, null=True)),
                ('backdrop_url', models.URLField(blank=True, max_length=500, null=True)),
                ('popularity', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=50, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='core.collection')),
                ('genres', models.ManyToManyField(to='core.genre')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='core.person')),
            ],
            options={
                'ordering': ['-popularity'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watchlist', 'In Watchlist'), ('watched', 'Watched'), ('watching', 'Watching')], default='watchlist', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='core_favori_user_id_cbe902_idx'), models.Index(fields=['created_at'], name='core_favori_created_8f3327_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.movie')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movie', 'parent', 'created_at'], name='core_commen_movie_i_475d64_idx'), models.Index(fields=['user'], name='core_commen_user_id_98f009_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='core.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acted_movies', to='core.person')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('movie', 'person')},
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id'], name='core_movie_tmdb_id_d46644_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='core_movie_title_e933de_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='core_movie_year_a638fe_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['popularity'], name='core_movie_popular_1fc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='core_movie_rating_fadf78_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'status'], name='core_watchl_user_id_ca70f3_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['created_at'], name='core_watchl_created_6b94f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
