# Generated by Django 5.1.1 on 2024-09-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('headshot', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('plot', models.TextField()),
                ('rating', models.FloatField()),
                ('year', models.IntegerField()),
                ('cover_url', models.URLField()),
                ('kind', models.CharField(max_length=50)),
                ('genres', models.ManyToManyField(to='core.genre')),
                ('cast', models.ManyToManyField(related_name='acted_movies', to='core.person')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='Filmography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmography', to='core.person')),
            ],
        ),
    ]
