# Generated by Django 5.1.5 on 2025-02-08 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='lists/thumbnails/')),
                ('backdrop', models.ImageField(upload_to='lists/backdrops/')),
                ('is_staff_pick', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lists', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_lists', to=settings.AUTH_USER_MODEL)),
                ('movies', models.ManyToManyField(related_name='lists', to='core.movie')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator'], name='core_list_creator_190d26_idx'), models.Index(fields=['created_at'], name='core_list_created_8202d0_idx'), models.Index(fields=['is_staff_pick'], name='core_list_is_staf_ba98f5_idx')],
            },
        ),
    ]
