# Generated by Django 5.1.5 on 2025-04-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='kind',
        ),
        migrations.AddField(
            model_name='movie',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='season_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
