# Generated by Django 5.1.5 on 2025-04-13 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_movie_kind_movie_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('still_url', models.URLField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.movie')),
            ],
            options={
                'unique_together': {('movie', 'season_number', 'episode_number')},
            },
        ),
    ]
