# Generated by Django 5.1.1 on 2024-09-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movie_cover_preview_url_alter_movie_cover_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='cover_preview_url',
            new_name='poster_preview_url',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='cover_url',
            new_name='poster_url',
        ),
    ]
