# Generated by Django 5.1.5 on 2025-02-14 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_person_options_person_biography_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='followers',
            field=models.ManyToManyField(related_name='followed_persons', through='core.PersonFollower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='personfollower',
            index=models.Index(fields=['user'], name='core_person_user_id_7d3764_idx'),
        ),
        migrations.AddIndex(
            model_name='personfollower',
            index=models.Index(fields=['person'], name='core_person_person__22b98b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personfollower',
            unique_together={('user', 'person')},
        ),
    ]
