# Generated by Django 5.1.5 on 2025-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_watchlist_delete_filmography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('not_wached', 'Not Watched'), ('watched', 'watched'), ('watching', 'Watching'), ('favorite', 'Favorite')], default='not_wached', max_length=12),
        ),
    ]
