# Generated by Django 5.1.5 on 2025-01-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_movie_cast_moviecast'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('watchlist', 'In Watchlist'), ('watched', 'Watched'), ('watching', 'Watching'), ('favorite', 'Favorite')], default='watchlist', max_length=12),
        ),
    ]
