# Generated by Django 5.1.5 on 2025-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the user profile is publicly visible'),
        ),
    ]
